language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty main'
      #- llvm-toolchain-trusty
      #- ubuntu-toolchain-r-test
    packages:
      - cmake-3.5
      # - clang-4.0
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
