language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
      - llvm-toolchain-trusty
      - ubuntu-toolchain-r-test
      - george-edison55-trusty-backports
    packages:
      - cmake-3.5
      # - clang-4.0
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
