language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
      - llvm-toolchain-trusty
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      # - clang-4.0
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
